language: python
jobs:
  include:
    - name: "Python 2.7 on Xenial Linux"
      python: "2.7"
    - name: "Python 3.4 on Xenial Linux"
      python: "3.4"
    - name: "Python 3.5 on Xenial Linux"
      python: "3.5"
    - name: "Python 3.6 on Xenial Linux"
      python: "3.6"
    - name: "Python 3.7 on Xenial Linux"
      python: "3.7"
    - name: "Python 3.8 on Xenial Linux"
      python: "3.8"
    - name: "Python 3.8-dev on Xenial Linux"
      python: "3.8-dev"
    - name: "Python nightly on Xenial Linux"
      python: "nightly"
install:
  - python setup.py -q install
  - pip install codecov coverage
script:
  - coverage run -m unittest
after_success:
  - codecov